### ISSUE TITLE
Baudrate "index out of range"

### ISSUE THREAD

**Issue by whoot** [grandideastudio/jtagulator#33] opened 2019-10-09 11:55 UTC
Hi,

i am having an issue with setting an extremely high baudrate.
With a Logic Analyzer I could successfully determine the baud rate of a UART interface, which is '506329'. However, this baudrate is not supported by JTAGulator and i´m getting a "Value out of range!" error message.

I know that this is a very unusual value and that it was probably used intentionally to make identification difficult.
But wouldn't it be better if JTAGulator didn't go through fixed values but a whole range of baud rates?

**Comment by joegrand** [comment] 2019-10-16 01:17
Having automatic baud rate detection instead of doing a table look-up of fixed values would be a nice feature, especially because vendors do like to use non-standard baud rates in order to make UART detection more "difficult." I took it out of the [TO DO](https://github.com/grandideastudio/jtagulator/blob/master/TODO.markdown) at some point, but I've put it back in.

It should be possible to use a timer to measure the minimum width of a detected signal and calculate the baud rate. This will result in false positives for any signal that isn't actually UART. Depending on the calculated speed (if it's high like your system), we wouldn't be able to display the corresponding data. That's because the object we're using for UART communication (JDCogSerial) supports non-standard baud rates up to 345600. This object is already highly optimized and it's unlikely the Propeller will be able to support baud rates higher than that in any universal fashion.

Since this is a feature request and not a bug, I'm closing the issue. However, I'm happy to merge any code that gets this done before I can!

**Closed by joegrand** 2019-10-16 01:17 UTC
